### ISSUE TITLE
TODO: Hide function

### ISSUE THREAD

**Issue by link2x** [link2x/l2x-link-shortener#1]
Hide will allow user to hide links from the main list (unless a "Show Hidden" filter is ticked).

Useful for all of my old RC codes that will now be defunct, as well as a few odds and ends that don't need to be immediately accessible.

- [x] Program a toggle for the hide button in `src/AdminLink.js`
- [x] Add a filter to the query in `pages/admin/index.js`
- [x] Add a toggle for the hide filter in `pages/admin/index.js`

**Comment by link2x** [comment]
Added in 2b7070c688e650568ef6bffb7212f3743e7cca2c.
